main:
  - name: "Research"
    url: "en/research/cv/"
    weight: 10

  - name: "Publications"
    url: "/en/publication/"
    weight: 20

  - name: "Projects"
    url: "/en/project/"
    weight: 30

  - name: "Resources"
    url: "/en/resources/datasets/"
    weight: 40

  - name: "News"
    url: "/en/post/"
    weight: 50

  - name: "Impact"
    url: "/en/impact/awards/"
    weight: 60

  - name: "People"
    url: "/en/people/"
    weight: 70

  - name: "Join"
    url: "/en/join/"
    weight: 80
